# Netlify Build Configuration
# Be aware that if you have conflicting configuration values, settings specified in
# netlify.toml override any corresponding settings in the Netlify UI.
# https://www.netlify.com/docs/netlify-toml-reference/

# Output directory and build command: npx tinacms build && eleventy
[build]
  publish = "_site"
  command = "npx eleventy"

# Cache generated content between builds (e.g. images)
[[plugins]]
package = "netlify-plugin-11ty"

  [plugins.inputs]
  cache_img = "assets/images/"
  cache_img_httpHeader = true
  cache_assets = "../.cache"

# Generate a CSP policy at Netlify build time using a build plugin
# Automatically generates SHA-256 hashes for inline <style> and <script> tags
# https://github.com/MarcelloTheArcane/netlify-plugin-csp-generator

[[plugins]]
  package = "netlify-plugin-csp-generator"

  [plugins.inputs]
    buildDir = "_site"
    reportOnly = false

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    scriptSrc = "'self' www.google-analytics.com www.googletagmanager.com"
    fontSrc = "'self' fonts.gstatic.com"
    imgSrc = "'self' www.google-analytics.com"
    connectSrc = "www.google-analytics.com"
    frameAncestors = "'none'"

[[plugins]]

	package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
		output_path = "reports/lighthouse/index.html"
    # run Lighthouse plugin before build
    fail_deploy_on_score_thresholds = "true"

	# optional, fails build when a category is below a threshold
	# [plugins.inputs.thresholds]
	# 	performance = 1.0
	# 	accessibility = 1.0
	# 	best-practices = 1.0
	# 	seo = 1.0