config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://chickin-lickin.netlify.app'
  site_title: alex.pics
  site_subtitle_1: Photos by Alex Johnstone
  site_subtitle_2: ''
  site_description: |
    Welcome to my site of favourite photos
  site_email: alex@alexjj.com
  site_social_url: ''
  site_icon_svg: /assets/icons/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  seo:
    site_title: Halide - Jamstack portfolio theme
    site_description: >-
      A customizable, minimalist portfolio website designed for photographers
      and still image creators.
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#c1c1c1'
    link_dark: '#ffffff'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  jpeg:
    enabled: true
    quality: 75
  webp:
    enabled: true
    quality: 75
  avif:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: GitHub
